spring:
  application:
    name: "transactions"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: "none"
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:transactions
    username: sa
    password: ''

server:
  port: 8090
