spring:
  application:
    name: "transactions"
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3307/transactionsdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    stream:
      bindings:
        send-communication-out-0:
          destination: send-communication
    openfeign:
      circuitbreaker:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "users"
    description: "User Management Application"
    version: "1.0.0"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000